# codeDeploy 동작
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    overwrite : yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user