spring:
  h2: #todo mysql로 변경예정
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true # 더미 데이터 적용
  mvc:
    path match:
      matching-strategy: ant_path_matcher #swagger
  sql:
    init:
      mode: always # 더미 데이터 적용
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: user
      password: 1234

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace #JPA 파라미터 콘솔에서 확인가능

cloud:
  aws:
    credentials:
      access-key: AKIA5KBHN5XQSBJBZBVK
      secret-key: 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
    s3:
      bucket: goods-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400
