spring:
  h2: #todo mysql로 변경예정
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true # 더미 데이터 적용
  mvc:
    path match:
      matching-strategy: ant_path_matcher #swagger
  sql:
    init:
      mode: always # 더미 데이터 적용


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace #JPA 파라미터 콘솔에서 확인가능