name: Java CI with Gradle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # spring 어플리케이션 Docker Image 빌드
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t shop_project .
#          docker tag shop_project shoppingmall:${GITHUB_SHA::7}
          docker push shoppingmall:${GITHUB_SHA::7}

      # 서버에서 Docker 이미지 실행
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          jost: ${{ secrets.EC2_WAS_IP }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker rmi $(docker images -q)
            docker pull shoppingmall:${GITHUB_SHA::7}
            docker tag shoppingmall:${GITHUB_SHA::7} shop_project
            docker stop shop_project
            docker rm shp_project
            docker run -d --name shop_project -p 8080:8080 shop_project