name: Java CI with Gradle
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

#      - name: make application.properties
#        run: |
#          cd ./src/main/resources
#          touch ./application.properties
#          echo "${{ secrets.PROPERTIES }}" > ./application.properties
#        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Docker build & push to production
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t shoppingmall .
          docker tag shoppingmall dbswhd493/shoppingmall:${GITHUB_SHA::7}
          docker push dbswhd493/shoppingmall:${GITHUB_SHA::7}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_WAS_IP }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull dbswhd493/shoppingmall:${GITHUB_SHA::7}
            docker tag dbswhd493/shoppingmall:${GITHUB_SHA::7} shoppingmall
            docker stop server
            doekcr run -d --name shop-application -p 8080:8080 shoppingmall 
