name: Java CI with Gradle
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

#      - name: make application.properties
#        run: |
#          cd ./src/main/resources
#          touch ./application.properties
#          echo "${{ secrets.PROPERTIES }}" > ./application.properties
#        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Docker build & push to production
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose up -d
          docker image tag mysql/mysql-server:8.0 dbswhd493/mysql:8.0
          docker image tag shop/application dbswhd493/application
          docker push dbswhd493/mysql:8.0
          docker push dbswhd493/application

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_WAS_IP }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull dbswhd493/dbswhd493
            docker-compose up -d
            docker image prune -f
