name: Java CI with Gradle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: 셋업 JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: application.properties 생성 및 복사
          run: |
            echo "mkdir & touch"
            mkdir -p ./src/main/resources 
            cd ./src/main/resources
            touch ./application.properties
            pwd
            ls -a .
            echo "copy properties"
            echo ${{ secrets.APPLICATION }} >> ./application.properties
            cat application.properties
          shell: bash

      - name: gradlew 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: gradle 빌드
        run: ./gradlew build
        shell: bash

      # spring 어플리케이션 Docker Image 빌드
      - name: 도커 build & 도커 허브 push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t dbswhd493/shop .
          docker push dbswhd493/shop

      # 서버에서 Docker 이미지 실행
      - name: 도커 허브 pull & 도커 run
        uses: appleboy/ssh-action@master
        with:
          jost: ${{ secrets.EC2_WAS_IP }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker rmi dbswhd493/shop
            sudo docker pull dbswhd493/shop
            sudo docker stop dbswhd493/shop
            sudo docker rm dbswhd493/shop
            sudo docker run -p 8080:8080 --name shop-application -d dbswhd493/shop