name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        -
      - name: Set up JDK 17
        uses: actions/setup-java@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t spring-cicd .
          docker tag spring-cicd ${{ DOCKER_LOGIN_ID }}/shoppingmall:${GITHUB_SHA::7}
          docker push ${{ DOCKER_LOGIN_ID }}/shoppingmall:${GITHUB_SHA::7}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 서버명[~~ap-northeast-2.compute.amazonaws.com로 시작하는 서버명을 적음]
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ DOCKER_LOGIN_ID }}/spring-cicd:${GITHUB_SHA::7}
            docker tag ${{ DOCKER_LOGIN_ID }}/spring-cicd:${GITHUB_SHA::7} spring-cicd
            docker stop server
            docker run -d --rm --name server -p 8080:8080 spring-cicd