name: Java CI with Gradle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: 셋업 JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties

      - name: gradlew 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: gradle 빌드
        run: ./gradlew build
        shell: bash

      # 서버에서 Docker 이미지 실행
      - name: 도커 허브 pull & 도커 run
        uses: appleboy/ssh-action@master
        with:
          jost: ${{ secrets.EC2_WAS_IP }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker rmi dbswhd493/shop
            sudo docker pull dbswhd493/shop
            sudo docker stop dbswhd493/shop
            sudo docker rm dbswhd493/shop
            sudo docker run -p 8080:8080 --name shop-application -d dbswhd493/shop